### ISSUE TITLE
How to use 'get' to return the entire table value.

### ISSUE THREAD

**Issue by madhurabhogate** [kontron/robotframework-snmplibrary#12]
I want to fetch the entire table and then use the information to process it.

*** Variables ***
${community}  public

*** Test Cases ***
SNMP polling for common OIDs
${connect_status} =  open snmp v2c connection  10.145.141.103  ${community}

1. ${snmp}=   Get IF-MIB::ifDescr.
ERROR: SmiError: Instance index ('',) to OID convertion failure at object 'ifDescr': Can't coerce '' into integer: ''

2. ${snmp}=   Get IF-MIB::ifDescr
ValueError: not enough values to unpack (expected 2, got 1)

3. ${snmp}=   Get  .1.3.6.1.2.1.2.2.1.2
Object with OID .1.3.6.1.2.1.2.2.1.2.0 not found

4. ${snmp}=   Get  .1.3.6.1.2.1.2.2.1.2  0
Object with OID .1.3.6.1.2.1.2.2.1.2.0 not found

Actual Output using snmp walk command on CLI-
mbhogate-mac:~ mbhogate$ snmpwalk -v2c -c public 10.145.141.103 .1.3.6.1.2.1.2.2.1.2
IF-MIB::ifDescr.33 = STRING: Ethernet33
IF-MIB::ifDescr.34 = STRING: Ethernet34
IF-MIB::ifDescr.1001 = STRING: Ethernet1/1
IF-MIB::ifDescr.2001 = STRING: Ethernet2/1
IF-MIB::ifDescr.3001 = STRING: Ethernet3/1
IF-MIB::ifDescr.4001 = STRING: Ethernet4/1
IF-MIB::ifDescr.5001 = STRING: Ethernet5/1
IF-MIB::ifDescr.6001 = STRING: Ethernet6/1
IF-MIB::ifDescr.7001 = STRING: Ethernet7/1
IF-MIB::ifDescr.8001 = STRING: Ethernet8/1

How to get the above CLI output using the SNMPLibrary ?

**Comment by hthiery** [comment]
The get a table use the Walk keyword.

http://kontron.github.io/robotframework-snmplibrary/SnmpLibrary.html#Walk

**Comment by madhurabhogate** [comment]
Thank you @hthiery

**Comment by mwalle** [comment]
can we close this issue?
